name: Webhook on Push, Pull Request, and Merge

on:
  push:
    branches:
      - main
      - staging
      - dev
  pull_request:
    branches:
      - main
      - staging
      - dev
  pull_request_review:
    types: [submitted]

jobs:
  send_webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Send Webhook
        run: |
          curl -X POST -H "Content-Type: application/json" -d '{"action": "${{ github.event.action }}", "repository": "${{ github.repository }}", "ref": "${{ github.ref }}", "actor": "${{ github.actor }}", "timestamp": "${{ github.event.created_at }}"}' https://action-repo.onrender.com

